branch-defaults:
  default:
    environment: doradus
global:
  application_name: doradus
  default_ec2_keyname: doradus-keypair
  default_platform: Multi-container Docker 1.6.2 (Generic)
  default_region: us-east-1
  profile: null
  sc: null
