function FileData_Pairs(x)
{
x.t("2.x","release");
x.t("available","cassandra");
x.t("describes","key");
x.t("key","configuration");
x.t("situations","note");
x.t("change","release");
x.t("certain","situations");
x.t("cassandra","2.x");
x.t("cassandra","options");
x.t("cassandra","configuration");
x.t("operation","cassandra");
x.t("operation","section");
x.t("common","options");
x.t("installations","described");
x.t("modification","certain");
x.t("options","change");
x.t("options","warrant");
x.t("options","described");
x.t("options","relevant");
x.t("options","covered");
x.t("section","describes");
x.t("release","options");
x.t("release","release");
x.t("windows","installations");
x.t("configuration","operation");
x.t("configuration","optional");
x.t("optional","available");
x.t("warrant","modification");
x.t("described","relevant");
x.t("note","cassandra");
x.t("relevant","cassandra");
x.t("relevant","windows");
x.t("covered","common");
}
