function FileData_Pairs(x)
{
x.t("files","doradus");
x.t("files","network");
x.t("doradus","security");
x.t("doradus","store");
x.t("doradus","unauthorized");
x.t("doradus","configuration");
x.t("access","requires");
x.t("security","options");
x.t("cassandra","database");
x.t("network","protocols");
x.t("requires","securing");
x.t("operation","doradus");
x.t("stored","cassandra");
x.t("store","application");
x.t("unauthorized","access");
x.t("options","doradus");
x.t("securing","doradus");
x.t("securing","configuration");
x.t("database","service");
x.t("configuration","files");
x.t("configuration","operation");
x.t("data","stored");
x.t("data","data");
x.t("application","data");
x.t("service","securing");
}
