function FileData_Pairs(x)
{
x.t("files","configuration");
x.t("describes","parameters");
x.t("discussed","previous");
x.t("change","clustered");
x.t("left","default");
x.t("sections","parameters");
x.t("however","values");
x.t("default","value");
x.t("doradus","configuration");
x.t("doradus.yaml","doradus");
x.t("doradus.yaml","file");
x.t("doradus.yaml","section");
x.t("doradus.yaml","configuration");
x.t("clustered","configurations");
x.t("configurations","enable");
x.t("file","except");
x.t("olap","caching");
x.t("operation","doradus");
x.t("parameters","left");
x.t("parameters","doradus.yaml");
x.t("section","describes");
x.t("enable","olap");
x.t("previous","sections");
x.t("configuration","files");
x.t("configuration","operation");
x.t("configuration","parameters");
x.t("value","however");
x.t("values","change");
x.t("except","discussed");
}
