function FileData_Pairs(x)
{
x.t("files","doradus");
x.t("enabled","described");
x.t("thrift","apis");
x.t("default","cassandra\u2019s");
x.t("apis","secured");
x.t("doradus","security");
x.t("doradus","configuration");
x.t("security","options");
x.t("cassandra","api");
x.t("api","default");
x.t("api","doradus");
x.t("api","described");
x.t("api","using");
x.t("operation","doradus");
x.t("communication","enabled");
x.t("encrypted","communication");
x.t("options","using");
x.t("securing","cassandra");
x.t("cassandra\u2019s","cql");
x.t("section","securing");
x.t("secured","encrypted");
x.t("secured","cql");
x.t("cql","thrift");
x.t("cql","api");
x.t("configuration","files");
x.t("configuration","operation");
x.t("described","section");
x.t("using","secured");
}
