function FileData_Pairs(x)
{
x.t("console","applications");
x.t("within","application");
x.t("doradus","doradus");
x.t("doradus","cassandra");
x.t("doradus","installing");
x.t("doradus","embedded");
x.t("cassandra","run");
x.t("cassandra","pure");
x.t("installing","running");
x.t("daemon","services");
x.t("jvm","doradus");
x.t("java","applications");
x.t("embedded","within");
x.t("windows","linux");
x.t("windows","services");
x.t("windows","run");
x.t("running","doradus");
x.t("linux","console");
x.t("services","doradus");
x.t("services","linux");
x.t("runs","jvm");
x.t("meaning","runs");
x.t("application","meaning");
x.t("applications","windows");
x.t("applications","run");
x.t("run","daemon");
x.t("run","windows");
x.t("pure","java");
}
