function FileData_Pairs(x)
{
x.t("managing","tenants");
x.t("creates","snapshot");
x.t("snapshot","deleted");
x.t("provided","command");
x.t("keyspace","applications");
x.t("/_tenants/","{tenant}");
x.t("delete","/_tenants/");
x.t("delete","tenant");
x.t("command","delete");
x.t("command","tenant\u2019s");
x.t("cassandra","creates");
x.t("via","following");
x.t("name","message");
x.t("rest","command");
x.t("tenants","delete");
x.t("body","provided");
x.t("tenant","delete");
x.t("tenant","name");
x.t("tenant","multi-tenant");
x.t("tenant","existing");
x.t("tenant","deleted");
x.t("multi-tenant","configuration");
x.t("tenant\u2019s","keyspace");
x.t("{tenant}","tenant");
x.t("{tenant}","{tenant}");
x.t("message","body");
x.t("existing","tenant");
x.t("configuration","managing");
x.t("data","recoverable");
x.t("data","deleted");
x.t("note","cassandra");
x.t("applications","data");
x.t("following","rest");
x.t("deleted","via");
x.t("deleted","data");
x.t("deleted","note");
}
